[package]
name = "confidential_utxo_2x2"
type = "bin"
authors = [""]

[dependencies]
utxo = { path = "../../lib/utxo" }
confidential_joinsplit = { path = "../../lib/confidential_joinsplit" }
shared = { path = "../../lib/shared" }